person:
  name: John Doe
  age: 30
  email: johndoe@example.com
  address:
    street: 123 Main St
    city: New York
    zip: 10001
  hobbies:
    - reading
    - cycling
    - swimming

